### PR TITLE
Bug Fix: Make number generator go from 0 to 36

### PR DESCRIPTION
**Pull request by ghost-writer-727**
Math.random() gives you a random decimal between 0 and 1, not including 1. Multiply it by 37 to expand the range: Now it's a decimal between 0 and 37, not including 37. Math.floor() rounds down to the nearest whole number, so you get a whole number between 0 and 36.

### CODE REVIEW

**Review by milsaware — APPROVED** [review]
Played it hundreds of times and I never picked up on the error. Thanks for the update

**Comment by tufabbedia-ctrl** [comment]
Roulette 
casino

**Comment by tufabbedia-ctrl** [comment]
Hi sir

**Comment by milsaware** [comment]
hello @tufabbedia-ctrl

**Pull request merged**
